urlRules = cons({allow:true,prefix:true,pattern:"#"},null);

// demo/batch.ur:28:69-29:3
urfuncs[1] = {c:"t",f:'{c:"l",b:{c:"l",b:{c:"=",e1:{c:"f",f:uw_mouseEvent,a:null},e2:{c:"f",f:rc,a:cons({c:"c",v:"/"},cons({c:"f",f:cat,a:cons({c:"c",v:"Batch/del/"},cons({c:"f",f:ts,a:cons({c:"v",n:2},null)},null))},cons({c:"c",v:function(s){var t=s.split("/");var i=0;return (i++,null)}},cons({c:"K"},cons({c:"c",v:false},null)))))}}}}'};
// demo/batch.ur:23:8-34:4
urfuncs[3] = {c:"t",f:'{c:"l",b:{c:"l",b:{c:"m",e:{c:"v",n:0},p:cons({p:{c:"c",v:null},b:{c:"c",v:""}},cons({p:{c:"s",n:false,p:{c:"r",l:cons({n:"1",p:{c:"r",l:cons({n:"1",p:{/*hoho*/c:"v"}},cons({n:"2",p:{/*hoho*/c:"v"}},null))}},cons({n:"2",p:{/*hoho*/c:"v"}},null))}},b:{c:"f",f:cat,a:cons({c:"c",v:"\\n\\074tr>\\074td>"},cons({c:"f",f:cat,a:cons({c:"f",f:ts,a:cons({c:"v",n:2},null)},cons({c:"f",f:cat,a:cons({c:"c",v:"\\074/td> \\074td>"},cons({c:"f",f:cat,a:cons({c:"f",f:eh,a:cons({c:"v",n:1},null)},cons({c:"f",f:cat,a:cons({c:"c",v:"\\074/td> "},cons({c:"f",f:cat,a:cons({c:"m",e:{c:"v",n:4},p:cons({p:{c:"c",v:true},b:{c:"f",f:cat,a:cons({c:"c",v:"\\074td>\\074button onclick=\'uw_event=event;exec("},cons({c:"f",f:cat,a:cons({c:"e",e:{c:"a",f:{c:"a",f:{c:"n",n:1},x:{c:"v",n:2}},x:{c:"c",v:null}}},cons({c:"c",v:")\'>Delete\\074/button>\\n\\074/td>"},null))},null))}},cons({p:{c:"c",v:false},b:{c:"c",v:""}},null))},cons({c:"f",f:cat,a:cons({c:"c",v:" \\074/tr>\\n"},cons({c:"f",f:cat,a:cons({c:"a",f:{c:"a",f:{c:"n",n:3},x:{c:"v",n:4}},x:{c:"v",n:0}},cons({c:"c",v:"\\n"},null))},null))},null))},null))},null))},null))},null))},null))}},null))}}}'};
// demo/batch.ur:35:26-38:26
urfuncs[2] = {c:"t",f:'{c:"l",b:{c:"l",b:{c:"l",b:{c:"f",f:sb,a:cons({c:"f",f:ss,a:cons({c:"v",n:1},null)},cons({c:"l",b:{c:"f",f:sr,a:cons({c:"f",f:cat,a:cons({c:"c",v:"\\074table>\\n\\074tr> \\074th>Id\\074/th> \\074th>A\\074/th> \\074/tr>\\n"},cons({c:"f",f:cat,a:cons({c:"a",f:{c:"a",f:{c:"n",n:3},x:{c:"v",n:3}},x:{c:"v",n:0}},cons({c:"c",v:"\\n\\074/table>"},null))},null))},null)}},null))}}}}'};
function _n1691(t,i){var x=t[i++];var r=x=="Cons"?{_1:{_1:parseInt(t[i++]),_2:uu(t[i++])},_2:(tmp=_n1691(t,i),i=tmp._1,tmp._2)}:x=="Nil"?null:pf("demo/batch.ur:67:50-67:84");return {_1:i,_2:r}}

// demo/batch.ur:67:14-67:91
urfuncs[4] = {c:"t",f:'{c:"l",b:{c:"l",b:{c:"=",e1:{c:"f",f:uw_mouseEvent,a:null},e2:{c:"=",e1:{c:"f",f:rc,a:cons({c:"c",v:"/"},cons({c:"c",v:"Batch/allRows/_"},cons({c:"c",v:function(s){var t=s.split("/");var i=0;return (tmp=_n1691(t,i),i=tmp._1,tmp._2)}},cons({c:"K"},cons({c:"c",v:false},null)))))},e2:{c:"f",f:sv,a:cons({c:"v",n:3},cons({c:"v",n:0},null))}}}}}'};
// demo/batch.ur:75:31-75:82
urfuncs[5] = {c:"t",f:'{c:"l",b:{c:"l",b:{c:"l",b:{c:"l",b:{c:"=",e1:{c:"f",f:uw_mouseEvent,a:null},e2:{c:"=",e1:{c:"f",f:sg,a:cons({c:"v",n:3},null)},e2:{c:"=",e1:{c:"f",f:sg,a:cons({c:"v",n:3},null)},e2:{c:"=",e1:{c:"f",f:sg,a:cons({c:"v",n:6},null)},e2:{c:"f",f:sv,a:cons({c:"v",n:7},cons({c:"r",l:cons({n:"1",v:{c:"r",l:cons({n:"1",v:{c:"a",f:{c:"c",v:pi},x:{c:"v",n:2}}},cons({n:"2",v:{c:"v",n:1}},null))}},cons({n:"2",v:{c:"v",n:0}},null))},null))}}}}}}}}}'};
// demo/batch.ur:16:16-16:19
urfuncs[7] = {c:"t",f:'{c:"l",b:{c:"m",e:{c:"v",n:0},p:cons({p:{c:"c",v:null},b:{c:"c",v:"Nil"}},cons({p:{c:"s",n:false,p:{/*hoho*/c:"v"}},b:{c:"f",f:cat,a:cons({c:"c",v:"Cons/"},cons({c:"f",f:cat,a:cons({c:"f",f:ts,a:cons({c:".",r:{c:".",r:{c:"v",n:0},f:"1"},f:"1"},null)},cons({c:"f",f:cat,a:cons({c:"c",v:"/"},cons({c:"f",f:cat,a:cons({c:"f",f:uf,a:cons({c:".",r:{c:".",r:{c:"v",n:0},f:"1"},f:"2"},null)},cons({c:"f",f:cat,a:cons({c:"c",v:"/"},cons({c:"a",f:{c:"n",n:7},x:{c:".",r:{c:"v",n:0},f:"2"}},null))},null))},null))},null))},null))}},null))}}'};
// demo/batch.ur:80:14-81:3
urfuncs[6] = {c:"t",f:'{c:"l",b:{c:"l",b:{c:"=",e1:{c:"f",f:uw_mouseEvent,a:null},e2:{c:"=",e1:{c:"f",f:rc,a:cons({c:"c",v:"/"},cons({c:"f",f:cat,a:cons({c:"c",v:"Batch/doBatch/"},cons({c:"a",f:{c:"n",n:7},x:{c:"f",f:sg,a:cons({c:"v",n:2},null)}},null))},cons({c:"c",v:function(s){var t=s.split("/");var i=0;return (i++,null)}},cons({c:"K"},cons({c:"c",v:false},null)))))},e2:{c:"f",f:sv,a:cons({c:"v",n:3},cons({c:"c",v:null},null))}}}}}'};

time_format = "%c";
